version: '3.4'
services:
  server:
    image: simpleton-server
    build:
      context: ./api
      dockerfile: ./Dockerfile
    volumes:
      - ./api:/usr/server
      - /usr/server/node_modules
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres/simpleton_db
      - NODE_ENV=development
    ports:
      - 9001:9001
    command: npm run dev
  client:
    image: simpleton-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/usr/client
      # - /usr/client/node_modules
    ports:
      - 5100:3000
    command: bash -c "npm run dev"
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=simpleton_db
