version: '3.4'
services:
  client:
    image: simpleton-client
    build:
      context: ./client
      dockerfile: ./Dockerfile
    volumes:
      - ./client:/usr/client
      # - /usr/client/node_modules
    ports:
      - 5100:3000
    # command: bash -c "npm run dev"
